### ISSUE TITLE
Failure to compile with flycheck 32

### ISSUE THREAD

**Issue by davidpham87** [borkdude/flycheck-clj-kondo#14]
Hello,

It seems that flycheck-clj-kondo can't compile on my machine with flycheck 32 (I use it for LSP).  The error is 

```
Autoloading file /home/david/.emacs.d/elpa/flycheck-clj-kondo-20201102.1128/flycheck-clj-kondo.el failed to define function flycheck-clj-kondo
```

Emacs version "28.0.50" (native-comp)
flycheck-clj-kondo 20201102.1128
flycheck 20201228.2104

Do you think my assumption are correct? 

Best regards,
David

**Comment by borkdude** [comment]
I'm running with Flycheck version: 32snapshot (package: 20201228.2104) from MELPA. Just re-installed it and I don't see any problems.

**Comment by borkdude** [comment]
Maybe try to erase your elpa directory, this sometimes helps.

**Comment by davidpham87** [comment]
Thanks a lot for your help! 

I double checked and lsp-mode and flycheck-clj-kondo don't play really well together. I removed all the reference and import to the package in my `.emacs.d` and let lsp use clj-kondo in the background.

**Comment by borkdude** [comment]
@davidpham87 This may apply to your situation: https://github.com/borkdude/flycheck-clj-kondo#multiple-linters

**Comment by davidpham87** [comment]
Thanks!
