### ISSUE TITLE
report unused vars as a warning?

### ISSUE THREAD

**Issue by andreyorst** [borkdude/flycheck-clj-kondo#15]
I'm not sure if this feature is present, because clojure-lsp highlights unused variables and displays a warning, but bare clj-kondo doesn't do it for me. I would like to set up a CI which will not pass when even a single warning is raised, and I would like to know about unused vars too.

**Comment by borkdude** [comment]
@andreyorst This issue doesn't really belong here but in clj-kondo itself. Having said that, you actually probably want to have [carve](https://github.com/borkdude/carve) in CI which is specialized to this behavior.

**Comment by andreyorst** [comment]
> This issue doesn't really belong here but in clj-kondo itself.

oops! I was sure I'm in the clj-kondo repo! Sorry!

So should I open an issue there? I still would like for clj-kondo to do it, so Emacs could report this without clojure-lsp, which I not always run

**Comment by borkdude** [comment]
@andreyorst You could check if there is already an issue for this, if not, you can create one.
