### ISSUE TITLE
allow adding custom args to defined checkers

### ISSUE THREAD

**Issue by genmeblog** [borkdude/flycheck-clj-kondo#23]
Can we have a possibility to pass additional arguments to `clj-kondo` through custom var?
I want to add `--dependencies` or `--copy-configs` for example. Currently arguments are hardcoded.

**Comment by genmeblog** [comment]
Possibly misunderstood the concept of `--copy-configs` which is rather one-time job for given setup. Anyway, I believe custom options for clj-kondo call might be useful.

**Comment by borkdude** [comment]
@genmeblog You can pass extra args with:

```
(flycheck-clj-kondo-define-checkers "--cache" ... you args here ...)
```

This will re-define all the checkers with your extra args. But as you said, `--copy-configs` is just a one time job and I don't recommend passing that to the checkers.

**Comment by genmeblog** [comment]
Right! I see. I was looking for some global var. Thanks!
