### ISSUE TITLE
Unable to see flycheck errors, flycheck-mode cannot be enabled

### ISSUE THREAD

**Issue by LiGoldragon** [borkdude/flycheck-clj-kondo#24]
On NixOS (bleeding edge), unable to get any output on flycheck mode, `list-errors` complains mode is disabled despite being manually enabled. The only deviation from running `clj-kondo` from cli is that emacs has one error less, and exits with ` Compilation exited abnormally with code 2 [...]`. The `verify-setup` seems happy. Flycheck works fine with nix. I lack information to chase this bug. Any pointers would be welcome. Thank you for making this package :pray:

**Comment by borkdude** [comment]
What do you get with flycheck-compile?

**Comment by LiGoldragon** [comment]
```
Syntax checkers for buffer main.clj in clojure-mode:

First checker to run:

  clj-kondo-clj
    - may enable: yes
    - may run:    t
    - executable: Found at /home/li/.nix-profile/bin/clj-kondo

Checkers that are compatible with this mode, but will not run until properly configured:

  clj-kondo-edn
    - may enable: yes
    - may run:    nil
    - executable: Found at /home/li/.nix-profile/bin/clj-kondo

Flycheck Mode is disabled.  Use C-u M-x flycheck-disable-checker to
enable disabled checkers.

--------------------

Flycheck version: 33snapshot (package: 20230813.620)
Emacs version:    29.1
System:           x86_64-pc-linux-gnu
Window system:    pgtk
```

**Comment by borkdude** [comment]
Can you follow up on this hint?

> Flycheck Mode is disabled.  Use C-u M-x flycheck-disable-checker to
enable disabled checkers.

**Comment by LiGoldragon** [comment]
I should have said that the value of `flycheck-disabled-checkers` is `nil`. After switching to clojure-ts-mode, it ended up being fixed, perhaps because of `:ensure t` or and/or because it had a double use-package entry. Sorry I couldnt hunt the bug better. Thank you so much :pray: 

[Fixing commit](https://github.com/sajban/kriomOS/commit/19c0c21a62c38334623187da5c0075abda483536)

**Comment by LiGoldragon** [comment]
Actually, the double-entry is one of the requirements for it to work, although my problem has changed (verify now fails from lacking an entry in `flycheck-checkers` I believe.) I added a TODO for later investigation. Moving on for now.
Thanks 
[Hacky commit](https://github.com/sajban/kriomOS/blob/76d1dbb75a30fcfe434a977cbc7f3b1f134653d1/nix/pkdjz/meikImaks/packages.el#L94)
