### ISSUE TITLE
Bump the Emacs and Flycheck requirements

### ISSUE THREAD

**Issue by bbatsov** [borkdude/flycheck-clj-kondo#28]
Flycheck requires Emacs 26 these days, so I think it makes sense for all extensions to do the same. I'd also suggest depending on a newer Flycheck version, as 0.18 is ancient. Probably it'd be best to depend on the latest stable version (currently 34) - Emacs package repos don't keep multiple versions of the same package and always serve the latest version.

**Comment by borkdude** [comment]
Not sure how to do this, but PR welcome

**Comment by arichiardi** [comment]
This does not seem to be relevant anymore if I read [this line](https://github.com/borkdude/flycheck-clj-kondo/blob/e38c67ba9db1ea1cbe1b61ab39b506c05efdcdbf/flycheck-clj-kondo.el#L11) correctly.

**Comment by borkdude** [comment]
Thanks @arichiardi !
