### ISSUE TITLE
Recent change causes spurious errors in deps.edn file

### ISSUE THREAD

**Issue by dpassen** [borkdude/flycheck-clj-kondo#6]
Since updating flycheck-clj-kondo to version 20200412.733 from Melpa, there are spurious errors in a simple deps.edn file.

<img width="848" alt="Screen Shot 2020-04-12 at 10 41 41 AM" src="https://user-images.githubusercontent.com/997822/79073098-38f3ae80-7caa-11ea-9610-40d88fcf5190.png">

**Comment by borkdude** [comment]
Sorry about that. I reverted #5.

**Comment by didibus** [comment]
Hum, that's probably the only thing I hadn't tested :p is a .edn file.

I'll see what I can do, it seems the issue is that flycheck is using lang `clj` instead of edn? That shouldn't have happened.

**Comment by didibus** [comment]
Ya, had a dumb syntax mistake, this should fix this: https://github.com/borkdude/flycheck-clj-kondo/pull/7 and maintain support for file-less buffers which fixes: https://github.com/flycheck/flycheck/issues/1665#
